open-feature/dotnet-sdk-contrib

CONTRIBUTING.md, build/Common.props
Not REALLY a fix: in preparation for 1.0, this permits SDK versions higher than `0.5.0+`, instead of just `0.5.0 - 0.6.0`.
=> fix: allow SDK versions 0.5+

src/OpenFeature.Contrib.Providers.GOFeatureFlag/GoFeatureFlagProvider.cs, src/OpenFeature.Contrib.Providers.GOFeatureFlag/GoFeatureFlagUser.cs, src/OpenFeature.Contrib.Providers.GOFeatureFlag/README.md, test/OpenFeature.Contrib.Providers.GOFeatureFlag.Test/GoFeatureFlagUserTest.cs
- fixes an issue
`System.Text.Json` does not serialize private members of a class. Since the class `GoFeatureFlagUser` had the following private members:
```
private string Key { get; set; }
private bool Anonymous { get; set; }
private Dictionary<string, object> Custom { get; set; }
```
When it was serialized as the User in `GOFeatureFlagRequest`, the Json that was returned was `{ "user": {},  ...` instead of `{ "user": { "key: :  ...`
This commit fixes this issue by making the property public and adding a test.
- updates documents
The name of the package was wrong it should be ***OpenFeature.Contrib.GOFeatureFla**g* and not *OpenFeature.Contrib.Providers.GOFeatureFlag*
=> fix:  GoFeatureFlagUser class was not serialized.

.github/workflows/lint-pr.yml, CONTRIBUTING.md, README.md
Changes:
- Added a message when a PR title is invalid
- Removed experimental badges
- Included additional resources on the readme
- Move release please information to the contributing section
Signed-off-by: Michael Beemer <beeme1mr@users.noreply.github.com>
=> chore: improve onboarding experience

.github/workflows/linux-ci.yml, .github/workflows/windows-ci.yml, build/Common.prod.props, src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, src/OpenFeature.Contrib.Providers.Flagd/README.md, src/OpenFeature.Contrib.Providers.Flagd/UnixDomainSocketConnectionFactory.cs
Closes #35 
As discussed in the issue, I have added net5.0 and above to the TargetFrameworks and used preprocessor directives to only make use of the unix socket support in compatible dotnet frameworks (net5.0 and above).
=> feat: unix socket support for flagd provider

src/OpenFeature.Contrib.Providers.GOFeatureFlag/GoFeatureFlagProvider.cs, test/OpenFeature.Contrib.Providers.GOFeatureFlag.Test/GoFeatureFlagProviderTest.cs
- Fix the issue with when flag is not found, the comparison was not working.
- Fix an issue when double are not recognized.
=> fix: some issues in the GO Feature Flag relay proxy

src/OpenFeature.Contrib.Providers.Flagd/Cache.cs, src/OpenFeature.Contrib.Providers.Flagd/FlagdConfig.cs, src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, src/OpenFeature.Contrib.Providers.Flagd/README.md, test/OpenFeature.Contrib.Providers.Flagd.Test/CacheTest.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdConfigTest.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdProviderTest.cs
Closes #37 
This PR implements standard caching functionality for the flagd provider. The configuration is done via the following env vars:
```
| Caching                      | FLAGD_CACHE                    | string  |           |     LRU       |
| Maximum cache size           | FLAGD_MAX_CACHE_SIZE           | number  | 10        |               |
| Maximum event stream retries | FLAGD_MAX_EVENT_STREAM_RETRIES | number  | 3         |               |
```
When caching is enabled, the flagd provider will establish an `EventStream` with the flagd server via grpc, and listen for `configuration_change` events. When such an event is received for a flag that has already been cached previously, that flag will be removed from the cache. When retrieving the value of a feature flag, the value will …
=> feat: implemented LRU caching for flagd provider 

src/OpenFeature.Contrib.Providers.Flagd/FlagdConfig.cs, src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, src/OpenFeature.Contrib.Providers.Flagd/README.md, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdConfigTest.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdProviderTest.cs
=> feat: support TLS connection in flagd provider

src/OpenFeature.Contrib.Providers.Flagd/FlagdConfig.cs, src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdProviderTest.cs
- introduces FlagdPorvider constructor accepting FlagdConfig as parameter
- exposes FlagdConfig as public class
- adds unit test for constructor
Fixes #56
=> feat: introduce FlagdProvider constructor accepting FlagdConfig as parameter

src/OpenFeature.Contrib.Providers.GOFeatureFlag/GoFeatureFlagProvider.cs, src/OpenFeature.Contrib.Providers.GOFeatureFlag/GoFeatureFlagProviderOptions.cs, src/OpenFeature.Contrib.Providers.GOFeatureFlag/GoFeatureFlagUser.cs, src/OpenFeature.Contrib.Providers.GOFeatureFlag/exception/UnauthorizedError.cs, test/OpenFeature.Contrib.Providers.GOFeatureFlag.Test/GoFeatureFlagProviderTest.cs, test/OpenFeature.Contrib.Providers.GOFeatureFlag.Test/GoFeatureFlagUserTest.cs
Since version `v1.7.0` GO Feature Flag relay proxy support an authorization key.
This PR make it possible to send this API Key to the proxy.
Fixes https://github.com/thomaspoignant/go-feature-flag/issues/666
=> feat: Support apiKey for GO Feature Flag relay proxy v1.7.0

.github/component_owners.yml, .github/workflows/component-owners.yml
- adds component owners, which are added as assignees/reviewers when the file path in question is modified in a PR.
=> chore: add component owners

src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, src/OpenFeature.Contrib.Providers.Flagd/README.md
Currently, this provider is listed on NuGet.org as being compatible with .Net Framework 4.6.2+.  While this does compile and link properly, it does not function at all with that.  .Net Framework 4.6.2+ requires TLS to be used with GRPC or else GRPC flat out doesn't work, specified here in their [documentation](https://learn.microsoft.com/en-us/aspnet/core/grpc/netstandard?view=aspnetcore-7.0#net-framework).
The code here verifies that the cert provided matches the server cert and ignores self signed errors for .Net Framework 4.6.2 through .Net Framework 4.8.1.
#73 
I also ran into a compiler error on line 336 with `new Empty()` not being the right type and fixed it.  My limited testing shows it had no adverse effects.
Create a self signed server certificate and launch the Flagd docker …
=> fix: NET462 requires TLS for GRPC to work

src/OpenFeature.Contrib.Providers.Flagd/FlagdConfig.cs, src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdConfigTest.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdProviderTest.cs
Provider can now be created with a `Uri`. Anything related to the URI is no longer read from environment variables, everything else is.
Fixes #71 
My unix socket knowledge is pretty slim, unit test in place to cover the basics and appears to do as expected.
N/A
=> fix: Setup config correct when passing a Uri (fixes #71)

src/OpenFeature.Contrib.Providers.Flagsmith/FlagsmithProvider.cs, src/OpenFeature.Contrib.Providers.Flagsmith/OpenFeature.Contrib.Providers.Flagsmith.csproj
- fixed possible exception when targetKey was not set in context.
=> fix: Flagsmith provider no key exception

src/OpenFeature.Contrib.Providers.Flagsmith/FlagsmithProvider.cs, src/OpenFeature.Contrib.Providers.Flagsmith/FlagsmithProviderConfiguration.cs, test/OpenFeature.Contrib.Providers.Flagsmith.Test/FlagsmithProviderTest.cs
- Removes targeting key (identity) from traits list to avoid unnecessary duplication
=> fix: do not send targeting key as separate trait in flagsmith

src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdProviderTest.cs
=> fix: Return correct name from FlagdProvider

src/OpenFeature.Contrib.Hooks.Otel/OpenFeature.Contrib.Hooks.Otel.csproj, src/OpenFeature.Contrib.Hooks.Otel/TracingHook.cs
The `OpenFeature.Contrib.Hooks.Otel` project currently references (1) an exporter implementation which libraries should _not_ do under any normal circumstances, and (2) the main `OpenTelemetry` package which is excessive given all of the excellent work by the `dotnet/runtime` and `open-telemetry/opentelemetry-dotnet` teams have done over the last couple of years to ensure that the BCL types in `System.Diagnostics` conform to OTel standards.
This commit removes (1) and pares down (2) to from `OpenTelemetry` to `OpenTelemetry.Api` to shrink the dependency footprint we ship to consumers.
_At this point, I would argue that this hooks package should meet the minimal dependency requirement for upstream inclusion in the main OpenFeature package, but deferring that discussion for now._
=> refactor: Reduce OTel dependencies

build/Common.prod.props, build/Common.props, src/Directory.Build.targets
- https://learn.microsoft.com/dotnet/core/compatibility/sdk/8.0/source-link
> ## [Using Source Link in .NET projects](https://github.com/dotnet/sourcelink?tab=readme-ov-file#using-source-link-in-net-projects)
> 
> Starting with .NET 8, Source Link for the following source control providers is included in the .NET SDK and enabled by default:
> - [GitHub](http://github.com) or [GitHub Enterprise](https://enterprise.github.com/home) 
> - [Azure Repos](https://azure.microsoft.com/en-us/services/devops/repos) git repositories (formerly known as Visual Studio Team Services)
> - [GitLab](https://gitlab.com) 12.0+ (for older versions see [GitLab settings](#gitlab))
> - [Bitbucket](https://bitbucket.org/) 4.7+ (for older versions see [Bitbucket settings](#bitbucket))
> 
> If your project uses .NET …
=> chore: SourceLink is built-in for .NET SDK 8.0.100+

src/OpenFeature.Contrib.Providers.Statsig/EvaluationContextExtensions.cs, src/OpenFeature.Contrib.Providers.Statsig/README.md, src/OpenFeature.Contrib.Providers.Statsig/StatsigProvider.cs, test/OpenFeature.Contrib.Providers.Statsig.Test/StatsigProviderTest.cs
The previous api took an `Action<StatsigServerOptions>`. While this was a nicer api, it did unfortunately not work as most of the fields on `StatsigServerOptions` can only be set in the constructor.
A few typos are also fixed
The updates in the README uncovers an example of the inconsistency mentioned [here](https://github.com/open-feature/dotnet-sdk-contrib/issues/154). I'm considering whether to rename the NuGet package (OpenFeature.Contrib.Provider**s**.Statsig) to match the Project name (OpenFeature.Contrib.Providers.Statsig)
=> fix: Update usage of StatsigServerOptions

.github/workflows/ci.yml, .github/workflows/release.yml
- installs the latest .net 8 sdk during build
https://github.com/open-feature/dotnet-sdk-contrib/pull/141 updates dotnet sdk to `8.0.203`. This is however not installed on github runners by default.
Fixes the error blocking https://github.com/open-feature/dotnet-sdk-contrib/pull/141
Similar issue [here](https://github.com/open-feature/dotnet-sdk/pull/218)
After merging this to the renovate branch, the actions on https://github.com/open-feature/dotnet-sdk-contrib/pull/141 should succeed.
=> fix: Install latest .net 8 sdk during build

src/OpenFeature.Contrib.Providers.Statsig/OpenFeature.Contrib.Providers.Statsig.csproj, src/OpenFeature.Contrib.Providers.Statsig/README.md
- fixes the name of the `OpenFeature.Contrib.Providers.Statsig` nuget package so it's now consistent with the project name
- updates README.md correspondingly
Relates to #154 
When this PR is merged, we should remove the versions with the wrong package name from nuget.org
As described in README.md
=> fix: Fix Statsig nuget package name

src/OpenFeature.Contrib.Providers.Statsig/README.md, src/OpenFeature.Contrib.Providers.Statsig/StatsigProvider.cs, test/OpenFeature.Contrib.Providers.Statsig.Test/StatsigProviderTest.cs
- updates the Statsig provider so it now returns the default value when a flag is not defined
Fix was made possible after the Statsig added the new `GetFeatureGate` API [here](https://github.com/statsig-io/dotnet-sdk/commit/f3ddca04360555fa98974c8837fed78624d557f1)
=> fix: Use new Statsig Api to return default value when flag is not defined

global.json, src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdProviderTest.cs
Fixes an issue where the provider's status was incorrectly set to error.
=> fix: provider status incorrect

release-please-config.json, src/OpenFeature.Contrib.Providers.FeatureManagement/README.md
Adding in a README.md for the FeatureManagement Provider
- Initial Documentation showing usage of the FeatureManagement Provider
Fixes #188 
FeatureManagement support is still in Preview. When a full release is integrated, the README should be updated accordingly.
=> chore: add FeatureManagement documentation

src/OpenFeature.Contrib.Providers.ConfigCat/ConfigCatProvider.cs, src/OpenFeature.Contrib.Providers.ConfigCat/OpenFeature.Contrib.Providers.ConfigCat.csproj
ConfigCat .NET SDK has recently [introduced error codes](https://github.com/configcat/.net-sdk/releases/tag/v9.2.0) to allow consumers to detect the reason for errors that occur during evaluation in a more reliable way than guessing it by matching error message strings.
This PR upgrades the OpenFeature provider for ConfigCat to the new SDK version and adjusts the provider implementation to leverage this new feature.
=> refactor: Use the newly introduced ConfigCat error codes to determine error type

src/OpenFeature.Contrib.Providers.Flagd/Resolver/InProcess/JsonEvaluator.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/JsonEvaluatorTest.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/Utils.cs
=> chore: additional unit tests for flagd provider

src/OpenFeature.Contrib.Providers.Flagd/FlagdConfig.cs, src/OpenFeature.Contrib.Providers.Flagd/FlagdProvider.cs, src/OpenFeature.Contrib.Providers.Flagd/README.md, test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdConfigTest.cs
Corrects the name/value of the in-process mode env var as per https://flagd.dev/providers/nodejs/?h=flagd_resolver#available-configuration-options
=> fix!: in-process var name/value (FLAGD_RESOLVER="in-process")

test/OpenFeature.Contrib.Hooks.Otel.Test/MetricsHookTest.cs
- fixes the `MetricsHookTest` by using `MeterProvider.ForceFlush()` rather than waiting for periodic flush to happen
The test in question would fail occasionally. This refactor will hopefully make them more stable, as there is the need to wait for an async process to complete has been removed.
=> fix: refactor OTEL metrics tests to make them more stable

.github/workflows/dotnet-format.yml, global.json, src/OpenFeature.Contrib.Providers.Statsig/EvaluationContextExtensions.cs, src/OpenFeature.Contrib.Providers.Statsig/OpenFeature.Contrib.Providers.Statsig.csproj, test/OpenFeature.Contrib.Providers.Statsig.Test/EvaluationContextExtensionsTests.cs
- adds mapping from [Evaluation Context](https://openfeature.dev/docs/reference/concepts/evaluation-context/) to [Statsig CustomID](https://docs.statsig.com/guides/experiment-on-custom-id-types).
- fixes dotnet format workflow so it uses `global.json` for dotnet version. Prior to this `.github/workflows/dotnet-format.yml` would fail when the dotnet version specified in `global.json` was greater than the one installed on the Github runner. 
- removes preview suffix from nuget package.
=> feat: map to Statsig CustomIDs

.github/component_owners.yml
- adds @LAttenborough as a component owner for the Statsig provider
=> chore: add extra component owner for the Statsig provider

build/Common.prod.props
Add net8.0 as a build target, as its the latest LTS version
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
upstream OpenFeature already supports this build target via [this commit](https://github.com/open-feature/dotnet-sdk/commit/cf2baa8a6b4328f1aa346bbea91160aa2e5f3a8d#diff-711ea17cbdebe419375c7684c8c39a1423d2bebcf8976ddd7bdd78deaab65b21)
=> chore: Add net8.0 as a build target, as its the latest LTS version

.github/workflows/ci.yml, src/OpenFeature.Contrib.Providers.Flagd/Resolver/InProcess/CustomEvaluators/FlagdProperties.cs, src/OpenFeature.Contrib.Providers.Flagd/Resolver/InProcess/CustomEvaluators/FractionalEvaluator.cs, src/OpenFeature.Contrib.Providers.Flagd/docker-compose.yaml, test/OpenFeature.Contrib.Providers.Flagd.E2e.Test/Steps/EvaluationStepDefinitionBase.cs, test/OpenFeature.Contrib.Providers.Flagd.Test/FractionalEvaluatorTest.cs
This PR adds support for relative weights in the fractional evaluator. This new (non breaking) feature has been proposed in https://github.com/open-feature/flagd/issues/1282 (The related PR to implement this in flagd is this one: https://github.com/open-feature/flagd/pull/1313).
In addition to supporting relative weights instead of percentages, the weight value for a distribution item can be omitted. In this case, a default weight of `1` will be applied.
Leaving this in draft until the related PR in flagd has been merged
=> feat: relative weights in fractional, fix injected props

src/OpenFeature.Contrib.Providers.Flagd/OpenFeature.Contrib.Providers.Flagd.csproj, src/OpenFeature.Contrib.Providers.Flagd/Resolver/InProcess/CustomEvaluators/FractionalEvaluator.cs, src/OpenFeature.Contrib.Providers.Flagd/Resolver/InProcess/CustomEvaluators/SemVerEvaluator.cs, src/OpenFeature.Contrib.Providers.Flagd/Resolver/InProcess/CustomEvaluators/StringEvaluator.cs
- Remove `Microsoft.Extensions.Logging` dependencies from `OpenFeature.Contrib.Providers.Flagd`
- Use `SemVersion.TryParse` to avoid a throw and catch
Fixes #232
=> fix: remove Microsoft.Extensions.Logging from flagd provider

.github/component_owners.yml
- Adds @adams85 (ConfigCat) to the component owner's list of the ConfigCat provider. The intention behind this is that we (ConfigCat) would like to mark the provider in this repo as the official ConfigCat OpenFeature .NET provider, and we would like to participate in its development and maintenance.
=> ci: add adams85 from ConfigCat as component owner

build/Common.props, src/OpenFeature.Contrib.Hooks.Otel/README.md, src/OpenFeature.Contrib.Providers.ConfigCat/README.md, src/OpenFeature.Contrib.Providers.FeatureManagement/README.md, src/OpenFeature.Contrib.Providers.Flagd/README.md, src/OpenFeature.Contrib.Providers.Flagsmith/README.md, src/OpenFeature.Contrib.Providers.GOFeatureFlag/README.md, src/OpenFeature.Contrib.Providers.Statsig/README.md
Updates the shared `OpenFeatureVer` to be less than 2.0, in preparation for our upcoming 2.0 release.
It would have been nice to have this from the get-go, but doing this now will help. I will subsequently release all artifacts.
Immediately after the 2.0 release I will update the contribs, and re-release with 2.0-3.0 compatibility.
see: https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort
=> chore: update OpenFeature version compatiblity

src/OpenFeature.Contrib.Providers.ConfigCat/ConfigCatProvider.cs, src/OpenFeature.Contrib.Providers.ConfigCat/OpenFeature.Contrib.Providers.ConfigCat.csproj, src/OpenFeature.Contrib.Providers.ConfigCat/README.md, src/OpenFeature.Contrib.Providers.ConfigCat/UserBuilder.cs, test/OpenFeature.Contrib.Providers.ConfigCat.Test/ConfigCatProviderTest.cs
As part of our official support for ConfigCat OpenFeatures providers, I revised the .NET provider and am proposing the following improvements and corrections:
* Let's implement `InitializeAsync` (so feature flag evaluation after awaiting `SetProviderAsync` will succeed) and `ShutdownAsync` (so the underlying client is disposed, i.e. the polling loop is stopped as soon as it's not needed any more).
* `UserBuilder` made some unnecessary heap memory allocations (e.g. when converting attribute keys to upper case). Let's eliminate these. (As feature flag evaluation can occur on hot paths, we should aim to minimize allocations to put as little pressure on the GC as possible.)
* When `id` or `identifier` is not specified in the evaluation context, a random user id is generated (a guid). I advise …
=> fix: Revise ConfigCat provider

test/OpenFeature.Contrib.Providers.Flipt.Test/FliptToOpenFeatureConverterTest.cs
- cleans unused theory params
- Utilized defined params in the test
- #295 
Fixes #295
=> fix: warnings in xunit tests due to unused theory params

src/OpenFeature.Contrib.Providers.Flipt/README.md
Updating the docs to force a republish.
=> fix: force a republish

.github/workflows/ci.yml, .github/workflows/release.yml, build/Common.prod.props, build/Common.props, build/Common.tests.props, global.json, src/OpenFeature.Contrib.Providers.Flipt/OpenFeature.Contrib.Providers.Flipt.csproj
This pull request includes several configuration and project files updates to streamline the build process and update dependencies. The most important changes include updating the .NET versions, modifying target frameworks, and improving the formatting of configuration files.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL33-R33): Replaced multiple `dotnet-version` lines with a single `global-json-file` reference to `global.json` for consistency. [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL33-R33) [[2]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL73-R70) [[3]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL103 …
=> build: Cleanup sdk version

renovate.json
This pull request includes a modification to the `renovate.json` file to update the configuration for dependency management. The change specifically updates the `extends` field and removes some configurations.
Configuration updates:
* [`renovate.json`](diffhunk://#diff-7b5c8955fc544a11b4b74eddb4115f9cc51c9cf162dbffa60d37eeed82a55a57L4-R4): Updated the `extends` field to use `github>open-feature/community-tooling` and removed the `semanticCommits` and `labels` configurations.
Check https://github.com/open-feature/dotnet-sdk/pull/364
=> chore: update Renovate configuration to extend community tooling

.github/workflows/release.yml
This pull request includes a minor change to the `.github/workflows/release.yml` file. The change adds a condition to the `.NET SDK` setup step to only run if releases are created.
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R29): Added a condition to the `.NET SDK` setup step to run only if `steps.release.outputs.releases_created` is true.
=> ci: Ensure conditional check for .NET SDK setup in release workflow

build/Common.tests.props, test/OpenFeature.Contrib.Providers.Flipt.Test/FlipExtensionsTest.cs, test/OpenFeature.Contrib.Providers.Flipt.Test/FliptExtensionsTest.cs, test/OpenFeature.Contrib.Providers.Flipt.Test/FliptProviderTest.cs, test/OpenFeature.Contrib.Providers.Flipt.Test/FliptToOpenFeatureConverterTest.cs, test/OpenFeature.Contrib.Providers.Flipt.Test/OpenFeature.Contrib.Providers.Flipt.Test.csproj
- Removes FluentAssertions from dotnet-sdk-contrib repository
Fixes #326
Looks like only the Flipt tests were referencing this so it was relatively straight forward. In some of the tests in the `FlipExtensionTests.cs` file I compare the Value/Structure classes via JSON. I looked at building some kind of Equality comparer but I think this approach might over complicate the solution. I've stuck with using the Xunit base assertions, we could opt to use something like shoudly in the future if readability is a concern.
=> test: Remove FluentAssertions

.github/workflows/ci.yml, .github/workflows/lint-pr.yml, .github/workflows/release.yml
This pull request updates several GitHub Actions workflows to explicitly define permissions for improved security and functionality. Additionally, it includes a minor change to the `lint-pr.yml` file for consistency in string formatting and an enhancement to the linting step.
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR21-R24): Added `contents: read` and `pull-requests: write` permissions to the `jobs` section for both the default CI job and the `e2e` job. [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR21-R24) [[2]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR51-R53)
* [`.github/workflows/lint-pr.yml`](diffhunk://#diff-70c3a017bfdb629fd50281fe5 …
=> ci: Fix CI permissions

.github/workflows/dotnet-format.yml, global.json, src/OpenFeature.Contrib.Providers.Flipt/OpenFeature.Contrib.Providers.Flipt.csproj
This pull request updates the build and formatting workflows, upgrades the .NET SDK version, and modifies the NSwag configuration to align with the new SDK version. These changes aim to improve compatibility, streamline the build process, and ensure proper code formatting.
* Updated the `.github/workflows/dotnet-format.yml` file to include `fetch-depth: 0` and `submodules: recursive` in the checkout step, ensuring all history and submodules are fetched.
* Added `dotnet restore` and `dotnet build --no-restore` steps to the workflow before running `dotnet format`, and modified the `dotnet format` command to include the `--no-restore` flag for efficiency.
* Updated the `global.json` file to use .NET SDK version `9.0.202`, replacing the previous version `8.0.408`.
* Updated the `Command` in …
=> chore(deps): update SDK version

test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdProviderTest.cs
This pull request adds calls to `flagdProvider.ShutdownAsync()` at the end of multiple test methods in `FlagdProviderTest.cs` to ensure proper resource cleanup after each test execution. These changes improve the test suite's reliability and maintainability.
* Added `await flagdProvider.ShutdownAsync();` to the following test methods to ensure the provider is properly shut down after each test:
- `TestResolveBooleanValueAsync`
- `TestResolveStringValue`
- `TestResolveIntegerValue`
- `TestResolveDoubleValue`
- `TestResolveStructureValue`
- `TestResolveFlagNotFound`
- `TestResolveGrpcHostUnavailable`
- `TestResolveTypeMismatch`
- `TestResolveUnknownError`
- `TestCacheAsync`
- `TestCacheHitAsync`
- `TestCacheInvalidationAsync`
- Additional test cases using `Utils.AssertUntilAsync` …
=> test: Fix flagd test shutdown

.github/workflows/release.yml
This pull request updates the `.github/workflows/release.yml` file to improve the handling of multiple release paths and streamline the release process. The key changes include adjustments to outputs, conditions, and environment variables, as well as the reintroduction of a previously commented-out step for attaching SBOMs to artifacts.
* **Updated Outputs for Release Package Job**: Changed outputs to include `all` (JSON object of all outputs) and `releases_created` (replacing `release_created`) for better handling of multiple release paths. (`[.github/workflows/release.ymlL22-R23](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L22-R23)`)
* **Condition Update in Release Job**: Modified …
=> ci: Fix SBOM path

test/OpenFeature.Contrib.Providers.Flagd.Test/FlagdConfigTest.cs
- Removes unused TestLogger in FlagdConfig tests
=> test: Remove unnecessary TestLogger in FlagdConfig tests

src/OpenFeature.Providers.Ofrep/OpenFeature.Providers.Ofrep.csproj
This pull request includes a minor update to the `OpenFeature.Providers.Ofrep` project file. The change specifies a `README.md` file to be included as the package's readme when published.
* [`src/OpenFeature.Providers.Ofrep/OpenFeature.Providers.Ofrep.csproj`](diffhunk://#diff-004af46220f914bdb2ad8fbbaa22391cd304171f62a52d551e6c93567c0ed39bR11): Added the `<PackageReadmeFile>` property to include `README.md` as the package readme.
=> docs: Ensure README.md is included as PackageReadmeFile in project configuration

src/OpenFeature.Contrib.Hooks.Otel/OpenFeature.Contrib.Hooks.Otel.csproj, src/OpenFeature.Contrib.Hooks.Otel/README.md
This pull request deprecates the `OpenFeature.Contrib.Hooks.Otel` library and introduces a migration guide to transition to the native OpenTelemetry hooks included in the OpenFeature .NET SDK starting with version 2.7.0. It also updates the `README.md` file to reflect the deprecation and provides detailed steps for migration and usage of the new hooks.
* [`src/OpenFeature.Contrib.Hooks.Otel/README.md`](diffhunk://#diff-c8546049ce6f5bf0f9a5268959b3f2db5b6300b0e7a43ecb4efcb23cbf28115cL3-R108): Marked the library as deprecated and added a detailed migration guide, including steps to update dependencies, using statements, hook class names, and code examples to transition to the native OpenTelemetry hooks in the OpenFeature …
=> docs: Add deprecation notice to OTEL lib

.github/workflows/ci.yml, .github/workflows/dotnet-format.yml, .github/workflows/release.yml
This pull request introduces caching for NuGet packages across multiple GitHub Actions workflows to improve build performance. The caching mechanism leverages the `actions/cache` action and is configured to store and restore NuGet packages based on the operating system and project files.
* **CI Workflow**: Added a step to cache NuGet packages in the `ci.yml` workflow, reducing redundant package downloads during builds. [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR46-R53) [[2]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR111-R118)
* **Dotnet Format Workflow**: Introduced NuGet package caching in the `dotnet-format.yml` workflow to optimize …
=> ci: Add caching to nuget to improve speed

.github/workflows/release.yml
This pull request updates the NuGet publishing workflow in `.github/workflows/release.yml` to improve security and automation. The main change is switching from a static NuGet API key to using GitHub OIDC-based authentication to obtain a short-lived API key for publishing packages.
**NuGet publishing workflow improvements:**
* Added a step to log in to NuGet using GitHub OIDC and generate a temporary API key for publishing (`NuGet/login` action).
* Updated the NuGet publish step to use the temporary API key from the login step instead of a static secret.
* Clarified the `id-token: write` permission with a comment explaining its purpose for OIDC token issuance.
Fixes #467
=> ci: change nuget publishing
